spring: 
  datasource: 
    url: jdbc:sqlserver://sourin-test.database.windows.net:1433;
         encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sourin98
    password: password@123
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      
server:
  port: 9005